# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies (skip prepare scripts to control build)
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts --production

# Copy source code
COPY src ./src

# Make server entry executable
RUN chmod +x src/server.js

# Expose no ports (stdio transport)

# Start server via stdio transport
ENTRYPOINT ["node", "src/server.js"]
